<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>karaburan_bringup</name>
  <version>0.0.0</version>
  <description>Production system bringup for the Karaburan boat.</description>
  <maintainer email="mleegwt@users.noreply.github.com">pi</maintainer>
  <license>TODO: License declaration</license>

  <depend>ament_index_python</depend>

  <exec_depend>boatcontrol</exec_depend>
  <exec_depend>bt785</exec_depend>
  <exec_depend>gpsd_client</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>lidar</exec_depend>
  <exec_depend>mpu9250</exec_depend>
  <exec_depend>navigation</exec_depend>
  <exec_depend>rosbag2</exec_depend>
  <exec_depend>rosbag2_storage_mcap</exec_depend>
  <exec_depend>sonar</exec_depend>
  <exec_depend>tempreader</exec_depend>
  <exec_depend>vl53l0x</exec_depend>

  <test_depend>ament_flake8</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
