version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.20
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001" # WebSockets port (optional)
    volumes:
      - ../mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ../mosquitto/data:/mosquitto/data
      - ../mosquitto/log:/mosquitto/log
    restart: unless-stopped
