services:
  mosquitto:
    image: eclipse-mosquitto:2.0.22
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001" # WebSockets port (optional)
    volumes:
      - ../mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ../mosquitto/data:/mosquitto/data
      - ../mosquitto/log:/mosquitto/log
    restart: unless-stopped

  mqttlogger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mqttlogger
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: "1883"
      MQTT_TOPIC: "karaburan/#"
      LOG_DIR: /mqttlog
    volumes:
      - ./mqttlog:/mqttlog
    depends_on:
      - mosquitto
    restart: unless-stopped

