adafruit-circuitpython-vl53l0x:
  ubuntu:
    pip:
      packages:
        - adafruit-circuitpython-vl53l0x
ament_python:
  ubuntu:
    apt:
      packages:
        - python3-setuptools
python3-junit2html:
  ubuntu:
    pip:
      packages:
        - junit2html==31.1.4
