version: '3.8'

services:
  influxdb:
    image: influxdb:2.7.6
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=organization
      - DOCKER_INFLUXDB_INIT_BUCKET=karaburan
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token
    volumes:
      - ../influxdb/influxdb-data/:/var/lib/influxdb2

  telegraf:
    image: telegraf:1.31.0
    container_name: telegraf
    depends_on:
      - influxdb
    environment:
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/rootfs/proc:ro
      - /sys:/rootfs/sys:ro
      - /etc:/rootfs/etc:ro
      - ../influxdb/telegraf.conf:/etc/telegraf/telegraf.conf:ro

volumes:
  influxdb-data:

