behavior_server:
  ros__parameters:
    use_sim_time: false
    behavior_plugins: ["spin", "back_up", "wait"]

    spin:
      plugin: "nav2_behaviors::Spin"
    back_up:
      plugin: "nav2_behaviors::BackUp"
    wait:
      plugin: "nav2_behaviors::Wait"

