controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]
    controller_frequency: 5.0

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"

      debug_trajectory_details: true
      min_vel_x: 0.0
      max_vel_x: 0.26
      min_vel_y: 0.0
      max_vel_y: 0.0
      max_vel_theta: 1.0
      min_speed_xy: 0.0
      max_speed_xy: 0.26
      min_speed_theta: 0.0

      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 3.2

      decel_lim_x: -1.0
      decel_lim_y: 0.0
      decel_lim_theta: -1.0

      vx_samples: 20
      vtheta_samples: 40

      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2

      critics: [
        "RotateToGoal",
        #        "ObstacleFootprint",
        "GoalAlign",
        "PathAlign",
        "PathDist",
        "GoalDist",
        "PreferForward"
      ]

