/controller_server:
  ros__parameters:
    use_sim_time: false
    odom_topic: "/odometry/filtered"
    controller_plugins: ["FollowPath"]
    controller_frequency: 10.0
    transform_tolerance: 0.1
    failure_tolerance: 2.0
    costmap_update_timeout: 1.0

    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]

    current_progress_checker: "progress_checker"
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.1
      movement_time_allowance: 10.0

    current_goal_checker: "goal_checker"
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.5
      yaw_goal_tolerance: 0.2
      stateful: true

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      lookahead_dist: 1.5
      desired_linear_vel: 0.25
      transform_tolerance: 0.5
      min_lookahead_dist: 0.3
      max_lookahead_dist: 3.0
      use_velocity_scaled_lookahead_dist: true
      enable_collision_checking: false
      min_x_velocity_threshold: 0.001
      min_theta_velocity_threshold: 0.001

/local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: local_enu
      robot_base_frame: base_link
      update_frequency: 5.0
      publish_frequency: 2.0
      rolling_window: true
      width: 1000
      height: 1000
      resolution: 5.0
      transform_tolerance: 0.5
      robot_radius: 0.6
      cost_scaling_factor: 10.0

      static_layer:
        enabled: false

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5
        cost_scaling_factor: 10.0

