/controller_server:

  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]

    local_costmap:
      global_frame: local_enu       # je GPS‑ENU frame
      robot_base_frame: base_link
      update_frequency: 5.0
      publish_frequency: 2.0
      rolling_window: true          # laat het window meebewegen met de robot
      width: 1000.0                 # 1 km breed
      height: 1000.0                # 1 km hoog
      resolution: 5.0               # 5 m per cell (200×200 cells voor 1 km²)
      transform_tolerance: 1.0
   
      plugins:
        - name: obstacle_layer
          type: "nav2_costmap_2d::ObstacleLayer"
        - name: inflation_layer
          type: "nav2_costmap_2d::InflationLayer"

    global_costmap:
      plugins: []
    
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"

      debug_trajectory_details: true
      min_vel_x: 0.0
      max_vel_x: 0.26
      min_vel_y: 0.0
      max_vel_y: 0.0
      max_vel_theta: 1.0
      min_speed_xy: 0.0
      max_speed_xy: 0.26
      min_speed_theta: 0.0

      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 3.2

      decel_lim_x: -1.0
      decel_lim_y: 0.0
      decel_lim_theta: -1.0

      vx_samples: 20
      vtheta_samples: 40

      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2

      critics: ["path_distance", "goal_align", "obstacle_footprint", "rotate_to_goal", "path_align", "goal_distance", "prefer_forward"]

      path_distance:
        max_distance_from_path: 0.2

      goal_align:
        angle_tolerance: 0.1

      obstacle_footprint:
        obstacle_threshold: 0.15

      rotate_to_goal:
        min_in_place_vel_theta: 0.4
        max_rotational_vel: 1.0

      path_align:
        heading_lookahead: 0.325

      goal_distance:
        tolerance: 0.1

      prefer_forward:
        large_heading_cost: 3.0
        small_heading_cost: 1.0

