ekf_filter_node:
  ros__parameters:
    frequency: 10.0
    sensor_timeout: 2.0
    initial_state_timeout: 10.0
    two_d_mode: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map #odom  # navsat_transform_node verandert dit naar 'map'

    publish_tf: true
    publish_acceleration: false

    imu0: /imu/data
    imu0_config: [false, false, false,  # pos (niet gebruikt)
                  true, true, true,     # rotatie (yaw)
                  false, false, false,  # lin. snelheid
                  false, false, false,  # rot. snelheid
                  true, true, true]     # oriëntatie (quaternion)
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true

    odom0: /odometry/gps
    odom0_config: [true, true, false,
               false, false, false,
               false, false, false,
               false, false, false]
    odom0_differential: false

    use_control: false

