navsat_transform_node:
  ros__parameters:
    frequency: 2.5
    delay: 1.0
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_utm_transform: false
    broadcast_cartesian_transform: true
    publish_filtered_gps: true

    use_odometry_yaw: false        # We hebben een IMU!
    use_local_cartesian: true      # Handig voor testgebieden
    wait_for_datum: false          # Gebruik eerste fix als referentie
    world_frame: map

    gps_topic: /fix/valid
    imu_topic: /imu/data
    odometry_topic: /odometry/gps
    base_link_frame: base_link

    imu_queue_size: 50
    gps_queue_size: 10
