/planner_server:
  ros__parameters:
    use_sim_time: false
    planner_frequency: 0.5
    expected_planner_frequency: 0.5

    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner::SmacPlanner2D"

    expected_planner_frequency: 20.0

/global_costmap:
  global_costmap:
    ros__parameters:
      global_frame: local_enu
      robot_base_frame: base_link
      rolling_window: true
      width: 1000
      height: 1000
      resolution: 1.0
      transform_tolerance: 0.5
      robot_radius: 0.5
      static_layer:
        enabled: false

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 2.0
        cost_scaling_factor: 8.0
