name: ROS2 Jazzy Build
on: push

jobs:
  jazzy_source:
    runs_on: ubuntu-latest
    container:
      image: ubuntu:noble
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: ros2
          target-ros2-distro: jazzy

